//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-12 16:24:43 by 余庆元
//     对此文件为固定的仓储基类继承，修改可能导致重新生成时被覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.Configuration;
using YF.Base.Data;
using App.Models;
using App.Repositories;
using App.Services.Dto;

namespace App.Services
{	
    	

	 public class BaseUserRoleMapService:IBaseUserRoleMap
    {
        IConnectionFactory connection = new ConnectionFactory();
        BaseUserRoleMapRepository repository;

        public BaseUserRoleMapService()
        {
            repository = new BaseUserRoleMapRepository(connection);
           // Mapper.CreateMap<BaseUserRoleMap, BaseUserRoleMapDto>();
           // Mapper.CreateMap<BaseUserRoleMapDto, BaseUserRoleMap>();

			//var cfg = new MapperConfigurationExpression();
			//cfg.CreateMap<BaseUserRoleMap, BaseUserRoleMapDto>();
			//cfg.CreateMap<BaseUserRoleMapDto, BaseUserRoleMap>();
			//Mapper.Initialize(cfg);
        }

        public BaseUserRoleMapService(IConnectionFactory con)
        {
           connection = con;
            repository = new BaseUserRoleMapRepository(connection);
        }

        public bool Add(BaseUserRoleMapDto dto)
        {
            BaseUserRoleMap model = Mapper.Map<BaseUserRoleMapDto, BaseUserRoleMap>(dto);
            return repository.Insert(model);
        }

        public bool Update(BaseUserRoleMapDto dto)
        {
           // throw new NotImplementedException();
          //  BaseUserRoleMap model = Mapper.Map<BaseUserRoleMapDto, BaseUserRoleMap>(dto);
            return repository.Update<BaseUserRoleMapDto>(dto);
        }

        public bool Delete(int id)
        {
            return repository.Delete(id);
        }

        public bool Delete(string ids)
        {
            return repository.Delete(ids);
        }

        public List<BaseUserRoleMapDto> GetAll()
        {
          //  AutoMapper.Mapper.CreateMap<Address, AddressDto>();
            var BaseUserRoleMapDtoList = Mapper.Map<List<BaseUserRoleMap>, List<BaseUserRoleMapDto>>(repository.GetList());
            return BaseUserRoleMapDtoList;
        }

        public List<BaseUserRoleMapDto> GetList(List<QueryBuilder> qbList)
        {
           // throw new NotImplementedException();
            var BaseUserRoleMapDtoList = Mapper.Map<List<BaseUserRoleMap>, List<BaseUserRoleMapDto>>(repository.GetList(qbList));
            return BaseUserRoleMapDtoList;
        }

        public List<BaseUserRoleMapDto> GetPageList(List<QueryBuilder> queryBuliders, SortCondition sort, int intPageSize, int intCurrentIndex, out int total)
        {
           // throw new NotImplementedException();
            
            var BaseUserRoleMapDtoList = Mapper.Map<List<BaseUserRoleMap>, List<BaseUserRoleMapDto>>(repository.QueryPage(queryBuliders,sort,intPageSize,intCurrentIndex,out total));
            return BaseUserRoleMapDtoList;
        }

        public List<BaseUserRoleMapDto> GetPageList(string sql, SortCondition sort, int intPageSize, int intCurrentIndex, out int total)
        {
            throw new NotImplementedException();
        }
    }

}

