//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-12 16:24:43 by 余庆元
//     对此文件为固定的仓储基类继承，修改可能导致重新生成时被覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.Configuration;
using Comba.Base.Data;
using App.Models;
using App.Repositories;
using App.Services.Dto;

namespace App.Services
{	

	 public class BaseRoleService:IBaseRole
    {
        IConnectionFactory connection = new ConnectionFactory();
        BaseRoleRepository repository;

        public BaseRoleService()
        {
            repository = new BaseRoleRepository(connection);
           // Mapper.CreateMap<BaseRole, BaseRoleDto>();
           // Mapper.CreateMap<BaseRoleDto, BaseRole>();

			//var cfg = new MapperConfigurationExpression();
			//cfg.CreateMap<BaseRole, BaseRoleDto>();
			//cfg.CreateMap<BaseRoleDto, BaseRole>();
			//Mapper.Initialize(cfg);
        }

        public bool Add(BaseRoleDto dto)
        {
            BaseRole model = Mapper.Map<BaseRoleDto, BaseRole>(dto);
            return repository.Insert(model);
        }

        public bool Update(BaseRoleDto dto)
        {
           // throw new NotImplementedException();
          //  BaseRole model = Mapper.Map<BaseRoleDto, BaseRole>(dto);
            return repository.Update<BaseRoleDto>(dto);
        }

        public bool Delete(int id)
        {
            return repository.Delete(id);
        }

        public bool Delete(string ids)
        {
            return repository.Delete(ids);
        }

        public List<BaseRoleDto> GetAll()
        {
          //  AutoMapper.Mapper.CreateMap<Address, AddressDto>();
            var BaseRoleDtoList = Mapper.Map<List<BaseRole>, List<BaseRoleDto>>(repository.GetList());
            return BaseRoleDtoList;
        }

        public List<BaseRoleDto> GetList(List<QueryBuilder> qbList)
        {
           // throw new NotImplementedException();
            var BaseRoleDtoList = Mapper.Map<List<BaseRole>, List<BaseRoleDto>>(repository.GetList(qbList));
            return BaseRoleDtoList;
        }

        public List<BaseRoleDto> GetPageList(List<QueryBuilder> queryBuliders, SortCondition sort, int intPageSize, int intCurrentIndex, out int total)
        {
           // throw new NotImplementedException();
            
            var BaseRoleDtoList = Mapper.Map<List<BaseRole>, List<BaseRoleDto>>(repository.QueryPage(queryBuliders,sort,intPageSize,intCurrentIndex,out total));
            return BaseRoleDtoList;
        }

        public List<BaseRoleDto> GetPageList(string sql, SortCondition sort, int intPageSize, int intCurrentIndex, out int total)
        {
            throw new NotImplementedException();
        }
    }

}

