//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-12 16:24:43 by 余庆元
//     对此文件为固定的仓储基类继承，修改可能导致重新生成时被覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using AutoMapper.Configuration;
using Comba.Base.Data;
using App.Models;
using App.Repositories;
using App.Services.Dto;

namespace App.Services
{	
    	

	 public class BaseUsersService:IBaseUsers
    {
        IConnectionFactory connection = new ConnectionFactory();
        BaseUsersRepository repository;

        public BaseUsersService()
        {
            repository = new BaseUsersRepository(connection);
           // Mapper.CreateMap<BaseUsers, BaseUsersDto>();
           // Mapper.CreateMap<BaseUsersDto, BaseUsers>();

			//var cfg = new MapperConfigurationExpression();
			//cfg.CreateMap<BaseUsers, BaseUsersDto>();
			//cfg.CreateMap<BaseUsersDto, BaseUsers>();
			//Mapper.Initialize(cfg);
        }

        public bool Add(BaseUsersDto dto)
        {
            BaseUsers model = Mapper.Map<BaseUsersDto, BaseUsers>(dto);
            return repository.Insert(model);
        }

        public bool Update(BaseUsersDto dto)
        {
           // throw new NotImplementedException();
          //  BaseUsers model = Mapper.Map<BaseUsersDto, BaseUsers>(dto);
            return repository.Update<BaseUsersDto>(dto);
        }

        public bool Delete(int id)
        {
            return repository.Delete(id);
        }

        public bool Delete(string ids)
        {
            return repository.Delete(ids);
        }

        public List<BaseUsersDto> GetAll()
        {
          //  AutoMapper.Mapper.CreateMap<Address, AddressDto>();
            var BaseUsersDtoList = Mapper.Map<List<BaseUsers>, List<BaseUsersDto>>(repository.GetList());
            return BaseUsersDtoList;
        }

        public List<BaseUsersDto> GetList(List<QueryBuilder> qbList)
        {
           // throw new NotImplementedException();
            var BaseUsersDtoList = Mapper.Map<List<BaseUsers>, List<BaseUsersDto>>(repository.GetList(qbList));
            return BaseUsersDtoList;
        }

        public List<BaseUsersDto> GetPageList(List<QueryBuilder> queryBuliders, SortCondition sort, int intPageSize, int intCurrentIndex, out int total)
        {
           // throw new NotImplementedException();
            
            var BaseUsersDtoList = Mapper.Map<List<BaseUsers>, List<BaseUsersDto>>(repository.QueryPage(queryBuliders,sort,intPageSize,intCurrentIndex,out total));
            return BaseUsersDtoList;
        }

        public List<BaseUsersDto> GetPageList(string sql, SortCondition sort, int intPageSize, int intCurrentIndex, out int total)
        {
            throw new NotImplementedException();
        }
    }

}

