//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-12 16:24:42 by 余庆元
//     对此文件为固定的仓储基类继承，修改可能导致重新生成时被覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using YF.Base.Data;
using App.Services.Dto;

namespace App.Services
{	
    	public interface IBaseTokens
    {
        bool Add(BaseTokensDto dto);

        bool Update(BaseTokensDto dto);

        bool Delete(int id);

        bool Delete(string ids);

        List<BaseTokensDto> GetAll();
        List<BaseTokensDto> GetList( List<QueryBuilder> qbList);
        List<BaseTokensDto> GetPageList(List<QueryBuilder> queryBuliders, SortCondition sort, int intPageSize, int intCurrentIndex, out int total);

        List<BaseTokensDto> GetPageList(string sql, SortCondition sort, int intPageSize, int intCurrentIndex, out int total);

    }
}
