//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-11-16 15:45:43 by 余庆元
//     对此文件为固定的仓储基类继承，修改可能导致重新生成时被覆盖。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Comba.Base.Data;
using App.Services.Dto;

namespace App.Services
{	
    	public interface ITasks
    {
        bool Add(TasksDto dto);

        bool Update(TasksDto dto);

        bool Delete(Guid id);

        bool Delete(string ids);

        List<TasksDto> GetAll();
        List<TasksDto> GetList( List<QueryBuilder> qbList);
        List<TasksDto> GetPageList(List<QueryBuilder> queryBuliders, SortCondition sort, int intPageSize, int intCurrentIndex, out int total);

        List<TasksDto> GetPageList(string sql, SortCondition sort, int intPageSize, int intCurrentIndex, out int total);

    }
}
