 
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-11-16 15:45:43 by 余庆元
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using App.Models;
using App.Services.Dto;
using AutoMapper;
using System;
using YF.Base.Data;
namespace App.Services
{	
	
	 public static class RegisterAutomapper
    {
		public static void Excute()
       {
           Mapper.Initialize(cfg => {
               cfg.CreateMap<BaseRole, BaseRoleDto>();
               cfg.CreateMap<BaseRoleDto, BaseRole>();
               cfg.CreateMap<BaseTokens, BaseTokensDto>();
               cfg.CreateMap<BaseTokensDto, BaseTokens>();
               cfg.CreateMap<BaseUserRoleMap, BaseUserRoleMapDto>();
               cfg.CreateMap<BaseUserRoleMapDto, BaseUserRoleMap>();
               cfg.CreateMap<BaseUsers, BaseUsersDto>();
               cfg.CreateMap<BaseUsersDto, BaseUsers>();
           });
        }
	}
}
 
 
