 
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-12-12 16:24:42 by 余庆元
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Comba.Base.Data;
namespace App.Models
{	
    	
	public class BaseUsers:EntityBase<int>
    {
										/// <summary>
		/// 用户名
		/// </summary>		
		public string UserName { get; set; }
	    						/// <summary>
		/// 登录账号
		/// </summary>		
		public string LoginId { get; set; }
	    						/// <summary>
		/// 密码
		/// </summary>		
		public string PassWord { get; set; }
	    						/// <summary>
		/// 权限
		/// </summary>		
		public string UserAuthority { get; set; }
	    						/// <summary>
		/// 0内置管理员，1普通用户
		/// </summary>		
		public byte? UserType { get; set; }
	    						/// <summary>
		/// 
		/// </summary>		
		public string CreateUser { get; set; }
	    						/// <summary>
		/// 
		/// </summary>		
		public Guid? CreateUserId { get; set; }
	    														/// <summary>
		/// 预留OpenID
		/// </summary>		
		public string OpenId { get; set; }
	    		 
    }
} 
