 
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2018-11-16 15:45:43 by 余庆元
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Comba.Base.Data;
namespace App.Models
{	
    	
	public class Tasks:EntityBase<Guid>
    {
										/// <summary>
		/// 任务编号
		/// </summary>		
		public string TaskCode { get; set; }
	    						/// <summary>
		/// 父级编号
		/// </summary>		
		public string ParentCode { get; set; }
	    						/// <summary>
		/// 任务名称
		/// </summary>		
		public string TaskName { get; set; }
	    						/// <summary>
		/// 任务负责人ID
		/// </summary>		
		public Guid? UserId { get; set; }
	    						/// <summary>
		/// 任务负责人
		/// </summary>		
		public string UserName { get; set; }
	    						/// <summary>
		/// 任务负责人账号
		/// </summary>		
		public string UserLoginId { get; set; }
	    						/// <summary>
		/// 参与人
		/// </summary>		
		public string Participant { get; set; }
	    						/// <summary>
		/// 计划开始时间
		/// </summary>		
		public DateTime? PlanTimeStart { get; set; }
	    						/// <summary>
		/// 计划结束时间
		/// </summary>		
		public DateTime? PlanTimeEnd { get; set; }
	    						/// <summary>
		/// 任务类型（0 IQC任务、1 其他任务）
		/// </summary>		
		public byte? TaskType { get; set; }
	    														/// <summary>
		/// 任务状态（0 未开始，1进行中，2已完成）
		/// </summary>		
		public byte? TaskState { get; set; }
	    						/// <summary>
		/// 关闭时间
		/// </summary>		
		public DateTime? CloseTime { get; set; }
	    						/// <summary>
		/// 实际开始时间
		/// </summary>		
		public DateTime? StartTime { get; set; }
	    						/// <summary>
		/// IQC 物料编号
		/// </summary>		
		public string IQCMaterialCode { get; set; }
	    						/// <summary>
		/// 
		/// </summary>		
		public int? MaterialBatch { get; set; }
	    						/// <summary>
		/// 
		/// </summary>		
		public bool? IsFail { get; set; }
	    						/// <summary>
		/// 
		/// </summary>		
		public string Approver { get; set; }
	    						/// <summary>
		/// 
		/// </summary>		
		public string Delegates { get; set; }
	    						/// <summary>
		/// 
		/// </summary>		
		public string templateid { get; set; }
	    		 
    }
} 
